{% set version = "0.22.0" %}

package:
  name: atlasgo
  version: {{ version }}

source:
  url: https://github.com/ariga/atlas/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 410696021a098bb949c3d91f89df295bd8cc98fa7f51c43a8a4c959f6e9fe7c3

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}      # [unix]
    - {{ stdlib('c') }}        # [unix]
    - {{ compiler('go-cgo') }} >=1.21
    - go-licenses

test:
  commands:
    - atlas version
    - atlas --help

about:
  home: https://atlasgo.io
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/
  summary: Manage your database schema as code
  doc_url: https://atlasgo.io/getting-started
  dev_url: https://github.com/ariga/atlas

extra:
  recipe-maintainers:
    - borchero
